version: '3.8'
services:
  gateway:
    build:
      context: ..
      dockerfile: Dockerfile.gateway
    ports:
      - '8080:8080'
    depends_on:
      - user
      - catalog
      - order
      - redis
    environment:
      - REDIS_ADDR=redis:6379

  user:
    build:
      context: ..
      dockerfile: services/user/Dockerfile
    ports:
      - '8081:8081'

  catalog:
    build:
      context: ..
      dockerfile: services/catalog/Dockerfile
    ports:
      - '8082:8082'

  order:
    build:
      context: ..
      dockerfile: services/order/Dockerfile
    ports:
      - '8083:8083'

  redis:
    image: redis:7
    ports:
      - '6379:6379'

ml-risk:
  build:
    context: ./ml
  ports:
    - "5000:5000"
  depends_on:
    - redis
